export interface VocabItem {
  fi: string
  vi: string
  en: string
  ex: string
  exVi: string
  exEn: string
}

export type Lang = "vi" | "en"

export const translations = {
  vi: {
    title: "Suomi Learner Pro",
    vocab: "Tu dien",
    review: "On tap",
    due: "Can on: ",
    finish: "Hoan thanh bai on hom nay!",
    exLabel: "Vi du: ",
    listen: "Nghe",
    groups: [
      "1. Chao hoi",
      "2. Dai tu",
      "3. Dong tu",
      "4. Danh tu",
      "5. Tinh tu",
      "6. So dem",
      "7. Cum cau",
    ],
  },
  en: {
    title: "Suomi Master Pro",
    vocab: "Dictionary",
    review: "Practice",
    due: "Due: ",
    finish: "All caught up for today!",
    exLabel: "Example: ",
    listen: "Listen",
    groups: [
      "1. Greetings",
      "2. Pronouns",
      "3. Verbs",
      "4. Nouns",
      "5. Adjectives",
      "6. Numbers",
      "7. Phrases",
    ],
  },
} as const

export const vocabGroups: Record<string, VocabItem[]> = {
  g0: [
    {
      fi: "hei",
      vi: "xin chao",
      en: "hello",
      ex: "Hei, mita kuuluu?",
      exVi: "Chao, ban khoe khong?",
      exEn: "Hello, how are you?",
    },
    {
      fi: "moi",
      vi: "chao (than mat)",
      en: "hi",
      ex: "Moi moi!",
      exVi: "Chao nhe!",
      exEn: "Bye bye!",
    },
    {
      fi: "nakemiin",
      vi: "tam biet",
      en: "goodbye",
      ex: "Nakemiin!",
      exVi: "Tam biet!",
      exEn: "Goodbye!",
    },
    {
      fi: "kiitos",
      vi: "cam on",
      en: "thank you",
      ex: "Kiitos avusta.",
      exVi: "Cam on su giup do.",
      exEn: "Thanks for the help.",
    },
    {
      fi: "anteeksi",
      vi: "xin loi",
      en: "sorry",
      ex: "Anteeksi.",
      exVi: "Xin loi.",
      exEn: "I'm sorry.",
    },
    {
      fi: "ole hyva",
      vi: "khong co chi",
      en: "welcome",
      ex: "Ole hyva!",
      exVi: "Khong co chi!",
      exEn: "You're welcome!",
    },
  ],
  g1: [
    {
      fi: "mina",
      vi: "toi",
      en: "I",
      ex: "Mina olen tassa.",
      exVi: "Toi o day.",
      exEn: "I am here.",
    },
    {
      fi: "sina",
      vi: "ban",
      en: "you",
      ex: "Kuka sina olet?",
      exVi: "Ban la ai?",
      exEn: "Who are you?",
    },
    {
      fi: "han",
      vi: "anh ay/co ay",
      en: "he/she",
      ex: "Han on opettaja.",
      exVi: "Nguoi ay la giao vien.",
      exEn: "S/he is a teacher.",
    },
    {
      fi: "tama",
      vi: "cai nay",
      en: "this",
      ex: "Mika tama on?",
      exVi: "Day la cai gi?",
      exEn: "What is this?",
    },
    {
      fi: "se",
      vi: "no",
      en: "it",
      ex: "Se on koira.",
      exVi: "No la mot con cho.",
      exEn: "It is a dog.",
    },
    {
      fi: "kylla",
      vi: "co",
      en: "yes",
      ex: "Kylla, kiitos.",
      exVi: "Vang, cam on.",
      exEn: "Yes, please.",
    },
    {
      fi: "ei",
      vi: "khong",
      en: "no",
      ex: "Ei, se ei ole.",
      exVi: "Khong, khong phai.",
      exEn: "No, it isn't.",
    },
  ],
  g2: [
    {
      fi: "olla",
      vi: "thi la",
      en: "to be",
      ex: "Haluan olla taalla.",
      exVi: "Toi muon o day.",
      exEn: "I want to be here.",
    },
    {
      fi: "menna",
      vi: "di",
      en: "to go",
      ex: "Menen nyt.",
      exVi: "Toi di bay gio.",
      exEn: "I go now.",
    },
    {
      fi: "tulla",
      vi: "den",
      en: "to come",
      ex: "Tule kotiin.",
      exVi: "Ve nha di.",
      exEn: "Come home.",
    },
    {
      fi: "nahda",
      vi: "thay",
      en: "to see",
      ex: "Naan sinut.",
      exVi: "Toi thay ban.",
      exEn: "I see you.",
    },
    {
      fi: "oppia",
      vi: "hoc",
      en: "to learn",
      ex: "Opin suomea.",
      exVi: "Toi hoc tieng Phan.",
      exEn: "I learn Finnish.",
    },
    {
      fi: "puhua",
      vi: "noi",
      en: "to speak",
      ex: "Puhun englantia.",
      exVi: "Toi noi tieng Anh.",
      exEn: "I speak English.",
    },
    {
      fi: "ymmartaa",
      vi: "hieu",
      en: "to understand",
      ex: "Ymmarran.",
      exVi: "Toi hieu.",
      exEn: "I understand.",
    },
  ],
  g3: [
    {
      fi: "ihminen",
      vi: "nguoi",
      en: "human",
      ex: "Olen ihminen.",
      exVi: "Toi la con nguoi.",
      exEn: "I am a human.",
    },
    {
      fi: "ystava",
      vi: "ban",
      en: "friend",
      ex: "Han on ystava.",
      exVi: "Do la mot nguoi ban.",
      exEn: "S/he is a friend.",
    },
    {
      fi: "perhe",
      vi: "gia dinh",
      en: "family",
      ex: "Minulla on perhe.",
      exVi: "Toi co gia dinh.",
      exEn: "I have a family.",
    },
    {
      fi: "koti",
      vi: "nha",
      en: "home",
      ex: "Menen kotiin.",
      exVi: "Toi ve nha.",
      exEn: "I go home.",
    },
    {
      fi: "vesi",
      vi: "nuoc",
      en: "water",
      ex: "Juon vetta.",
      exVi: "Toi uong nuoc.",
      exEn: "I drink water.",
    },
  ],
  g4: [
    {
      fi: "hyva",
      vi: "tot",
      en: "good",
      ex: "Tama on hyva.",
      exVi: "Cai nay tot.",
      exEn: "This is good.",
    },
    {
      fi: "uusi",
      vi: "moi",
      en: "new",
      ex: "Uusi auto.",
      exVi: "Xe hoi moi.",
      exEn: "A new car.",
    },
    {
      fi: "suuri",
      vi: "lon",
      en: "big",
      ex: "Suuri talo.",
      exVi: "Ngoi nha lon.",
      exEn: "A big house.",
    },
    {
      fi: "pieni",
      vi: "nho",
      en: "small",
      ex: "Pieni poika.",
      exVi: "Cau be nho.",
      exEn: "A small boy.",
    },
  ],
  g5: [
    {
      fi: "yksi",
      vi: "1",
      en: "one",
      ex: "Yksi kahvi.",
      exVi: "Mot ca phe.",
      exEn: "One coffee.",
    },
    {
      fi: "kaksi",
      vi: "2",
      en: "two",
      ex: "Kaksi vetta.",
      exVi: "Hai nuoc.",
      exEn: "Two waters.",
    },
    {
      fi: "kymmenen",
      vi: "10",
      en: "ten",
      ex: "Kymmenen euroa.",
      exVi: "Muoi Euro.",
      exEn: "Ten Euros.",
    },
  ],
  g6: [
    {
      fi: "Mina olen opiskelija",
      vi: "Toi la sinh vien",
      en: "I am a student",
      ex: "Olen opiskelija taalla.",
      exVi: "Toi la sinh vien o day.",
      exEn: "I'm a student here.",
    },
    {
      fi: "Puhun vahan suomea",
      vi: "Toi noi chut tieng Phan",
      en: "I speak a bit of Finnish",
      ex: "Anteeksi, puhun vahan suomea.",
      exVi: "Xin loi, toi noi chut tieng Phan.",
      exEn: "Sorry, I speak a bit of Finnish.",
    },
  ],
}

export function getAllWords(): VocabItem[] {
  return Object.values(vocabGroups).flat()
}
